<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZiraatProje.Business\ZiraatProje.Business.csproj" />
    <ProjectReference Include="..\ZiraatProje.DataAccess\ZiraatProje.DataAccess.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\ziraat_logo.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
